# Generated by Django 2.2.6 on 2019-10-31 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('seller_id', models.CharField(db_index=True, max_length=100)),
            ],
            options={
                'unique_together': {('email', 'seller_id')},
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Seller')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAnalysisResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('title_score', models.IntegerField()),
                ('title_character_count', models.IntegerField()),
                ('title_contains_promo_phrase', models.BooleanField()),
                ('title_contains_single_quote', models.BooleanField()),
                ('title_contains_ascii', models.BooleanField()),
                ('title_contains_seo_adverse_chars', models.BooleanField()),
                ('title_num_lower_case', models.IntegerField()),
                ('title_num_all_caps', models.IntegerField()),
                ('title_num_incorrect_caps', models.IntegerField()),
                ('title_contains_dollar_sign', models.BooleanField()),
                ('description_score', models.IntegerField()),
                ('description_character_count', models.IntegerField()),
                ('description_contains_quotes', models.BooleanField()),
                ('description_contains_html', models.BooleanField()),
                ('description_contains_price_condition_info', models.BooleanField()),
                ('description_contains_shipping_info', models.BooleanField()),
                ('description_contains_contact_info', models.BooleanField()),
                ('description_num_lower_case_bullets', models.IntegerField()),
                ('description_num_bullets', models.IntegerField()),
                ('media_score', models.IntegerField()),
                ('media_num_images', models.IntegerField()),
                ('media_low_qual_images', models.IntegerField()),
                ('media_high_whitespace_images', models.IntegerField()),
                ('media_num_videos', models.IntegerField()),
                ('ratings_reviews_score', models.IntegerField()),
                ('rating', models.FloatField()),
                ('num_reviews', models.IntegerField()),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Seller')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Submission')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results_url', models.URLField(blank=True, null=True)),
                ('copy_score', models.FloatField()),
                ('media_score', models.FloatField()),
                ('feedback_score', models.FloatField()),
                ('extra_content_score', models.FloatField()),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Seller')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Submission')),
            ],
        ),
    ]
