# Generated by Django 2.2.6 on 2019-11-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_productanalysisresult_bullets_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='productanalysisresult',
            name='feature_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
