# Generated by Django 2.2.6 on 2019-11-20 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_productanalysisresult_feature_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='seller_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='seller_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
