# Generated by Django 2.2.6 on 2019-11-22 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20191120_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisresult',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Submission'),
        ),
    ]
