# Generated by Django 2.2.6 on 2019-12-12 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20191122_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='productanalysisresult',
            name='extra_content_score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
