# Generated by Django 2.2.6 on 2019-12-30 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_productanalysisresult_extra_content_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='webflow_cms_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
