# Generated by Django 2.2.8 on 2020-01-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_analysisresult_webflow_cms_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='limit_results',
            field=models.IntegerField(default=20, help_text="Use '0' for no limit"),
        ),
    ]
