# Generated by Django 2.2.8 on 2020-01-27 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200122_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('processing', 'Processing'), ('success', 'Success'), ('failure', 'Failure')], default='submitted', max_length=10),
        ),
    ]
