# Generated by Django 2.2.8 on 2020-01-31 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_submission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
