# Generated by Django 2.2.8 on 2020-02-19 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_submission_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='notes',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
