# Generated by Django 2.2.10 on 2020-02-24 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200219_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='source',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('website', 'Website'), ('resubmission', 'Resubmission')], max_length=12),
        ),
    ]
